#!/usr/bin/env python3
"""
Script to generate filtered gene families from MMseqs2 clustering output.

Only strict 1-to-1 orthologous clusters are retained, meaning that each cluster must contain exactly one gene from each genome. Clusters that do not meet this criterion are skipped and logged.

Input:
- clusters_cluster.tsv generated by MMseqs2 (../results/clusters/mmseqs2/)

Output:
- orthologs_relaxed.tsv containing filtered 1-to-1 orthologous gene families

Paralogous clusters are filtered out by rejecting any cluster that contains more than one gene originating from the same genome.

6th part of pipeline
"""


# ~~~~~ Imports ~~~~~
from collections import defaultdict, Counter
import argparse
from pathlib import Path


# ~~~~~ Arguments ~~~~~
def parse_args():
    parser = argparse.ArgumentParser(
        description="Script to generate filtered gene families from MMseqs2 clustering output."
    )

    parser.add_argument(
        "--input",
        type=Path,
        required=True,
        help="Path to clusters_clusters.tsv file (MMseqs2 output)",
    )
    parser.add_argument(
        "--n_genomes",
        type=int,
        required=True,
        help="Number of genomes/proteomes in the analysis",
    )

    parser.add_argument("--output", required=True, type=Path)

    return parser.parse_args()


# ~~~~~~ Functions ~~~~~
def species_from_id(gene_id: str) -> str:
    """Extract species name from gene ID."""
    return gene_id.split("|")[0]


def load_clusters(input_file: Path) -> dict:
    """Group genes by their representative sequence IDs into dictionary."""
    clusters = defaultdict(list)

    with input_file.open() as infile:
        for line in infile:
            rep_id, member_id = line.rstrip("\n").split("\t")
            clusters[rep_id].append(member_id)

    return clusters


# ~~~~~ Main logic ~~~~~


def main():
    args = parse_args()

    clusters = load_clusters(args.input)

    total_clusters = len(clusters)
    kept_clusters = 0
    rejected_too_small = 0
    rejected_paralogs = 0

    with args.output.open("w") as out:
        out.write("cluster_id\tspecies\tgene_id\n")

        for rep_id, members in clusters.items():
            by_species = defaultdict(list)
            # reject clusters smaller than n_genomes - every cluster should have exactly one gene from each genome
            if len(members) < args.n_genomes:
                rejected_too_small += 1
                continue

            for gene in members:
                by_species[species_from_id(gene)].append(gene)

            selected = []
            paralog = False

            for genes in by_species.values():
                if len(genes) > 1:
                    paralog = True
                selected.append(sorted(genes)[0])

            if paralog:
                rejected_paralogs += 1
                continue

            kept_clusters += 1

            for gene in selected:
                out.write(f"{rep_id}\t{species_from_id(gene)}\t{gene}\n")

    # --------- statistics ---------

    with open("filter.stats.tsv", "w") as stats:
        stats.write("metric\tvalue\n")
        stats.write(f"input_clusters\t{total_clusters}\n")
        stats.write(f"kept_clusters\t{kept_clusters}\n")
        stats.write(f"rejected_too_small\t{rejected_too_small}\n")
        stats.write(f"rejected_paralogs\t{rejected_paralogs}\n")
        stats.write(f"n_genomes\t{args.n_genomes}\n")


if __name__ == "__main__":
    main()
